apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dns-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dns-api
  template:
    metadata:
      labels:
        app: dns-api
    spec:
      containers:
      - name: dns-api
        image: dns-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000